
CREATE OR REPLACE PROCEDURE GetOrdersAndCustomersByDateRange(
    START_DATE DATE,
    END_DATE DATE
)
RETURNS VARCHAR
LANGUAGE SQL
AS $$

    -- Query first table: Orders
    LET joined_result RESULTSET := (SELECT A.*, B.* 
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS A 
    JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER B 
        ON A.O_CUSTKEY = B.C_CUSTKEY
        WHERE A.O_ORDERDATE BETWEEN :START_DATE AND :END_DATE
        ORDER BY A.O_ORDERDATE DESC);

RETURN TABLE(joined_result);
$$;



